# Generated by Django 4.2.1 on 2024-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='maker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
