# Generated by Django 4.2.1 on 2024-03-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_maker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_user', 'View user'), ('edit_user', 'Edit user'), ('delete_user', 'Delete user'), ('create_user', 'Create user'), ('revoke_token', 'Revoke token'), ('suspend_user', 'Suspend user')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
